### ISSUE TITLE
Failed to activate extension: Failed to execute command "npm" with arguments "rebuild, grpc, --target=9.2.1, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1

### ISSUE THREAD

**Issue by BenCemlyon** [IBM-Blockchain/blockchain-vscode-extension#2768]
Could not rebuild native dependencies Failed to execute command "npm" with arguments "rebuild, grpc, --target=9.2.1, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed

Visual Studio Code version : 1.50.1

Thank you

**Comment by Raymondvzonneveld** [comment]
I am experiencing the same issue. 

I installed vscode and adde Code to path. 
I installed all prerequisites and checked the versions.
Everything should work fine, but unfortunately it doesn't

code version :1.50.1
Docker version 19.03.13
npm version: 6.14.8
node version: v14.15.0
Xcode version 2373

working on macOS Catalina Version 10.15.5

**Comment by Jakeeyturner** [comment]
Hi @BenCemlyon,

Please can you paste the whole output log?

**Comment by BenCemlyon** [comment]
Hi @Jakeeyturner 

Where can i see more logs please ?

Thank you for  your help

![image](https://user-images.githubusercontent.com/73529173/98000234-95582000-1dec-11eb-92f0-f2f061e44611.png)

![image](https://user-images.githubusercontent.com/73529173/98000729-19aaa300-1ded-11eb-9922-342698ac6407.png)

**Comment by Jakeeyturner** [comment]
Hey,

<img width="1275" alt="Screenshot 2020-11-03 at 15 15 24" src="https://user-images.githubusercontent.com/10009752/98004082-67bca800-1de7-11eb-91aa-da3f908002ae.png">

You need to click on `Output` and make sure `Blockchain` is selected from the dropdown (on the right).

**Comment by BenCemlyon** [comment]
Oh yeah sorry, here are the logs :

[03/11/2020 à 15:54:45] [IMPORTANT] Log files can be found by running the `Developer: Open Logs Folder` command from the palette

[03/11/2020 à 15:54:45] [INFO] Starting IBM Blockchain Platform Extension
[03/11/2020 à 15:54:45] [INFO] Attempting to require dependency: grpc
[03/11/2020 à 15:54:48] [INFO] Error requiring dependency: Failed to load c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\node_modules\grpc\src\node\extension_binary\electron-v9.2-win32-x64-unknown\grpc_node.node. Cannot find module 'c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\node_modules\grpc\src\node\extension_binary\electron-v9.2-win32-x64-unknown\grpc_node.node'
Require stack:
- c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\node_modules\grpc\src\grpc_extension.js
- c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\node_modules\grpc\src\client_interceptors.js
- c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\node_modules\grpc\src\client.js
- c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\node_modules\grpc\index.js
- c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\build\extension\dependencies\DependencyManager.js
- c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\build\extension\webview\PreReqView.js
- c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\build\extension\util\ExtensionUtil.js
- c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\build\extension\util\Reporter.js
- c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\build\extension\extension.js
- c:\Users\coste\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\coste\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\coste\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
[03/11/2020 à 15:54:48] [INFO] Updating native node modules
[03/11/2020 à 15:54:48] [INFO] Rebuilding native node modules
[03/11/2020 à 15:55:12] [INFO] npm
[03/11/2020 à 15:55:12] [INFO]  ERR! code 1
[03/11/2020 à 15:55:12] [INFO] npm ERR! path c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\node_modules\grpc
[03/11/2020 à 15:55:12] [INFO] npm 
[03/11/2020 à 15:55:12] [INFO] ERR! command failed
[03/11/2020 à 15:55:12] [INFO] npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "node-pre-gyp install --fallback-to-build --library=static_library"
[03/11/2020 à 15:55:12] [INFO] npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\node_modules\grpc\src\node\extension_binary\electron-v9.2-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\node_modules\grpc\src\node\extension_binary\electron-v9.2-win32-x64-unknown --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v9.2 --dist-url=https://atom.io/download/electron' (1)
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp info it worked if it ends with ok
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp info using node-pre-gyp@0.14.0
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp info using node@15.0.1 | win32 | x64
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download 
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/electron-v9.2-win32-x64-unknown.tar.gz
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp http 404 https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/electron-v9.2-win32-x64-unknown.tar.gz
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/electron-v9.2-win32-x64-unknown.tar.gz 
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp WARN Pre-built binaries not found for grpc@1.24.2 and electron@9.2.1 (electron-v9.2 ABI, unknown) (falling back to source compile with node-gyp) 
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp http 404 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/electron-v9.2-win32-x64-unknown.tar.gz 
[03/11/2020 à 15:55:12] [INFO] npm 
[03/11/2020 à 15:55:12] [INFO] ERR! gyp info it worked if it ends with ok
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp info using node-gyp@7.1.2
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp info using node@15.0.1 | win32 | x64
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp info ok 
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp info it worked if it ends with ok
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp info using node-gyp@7.1.2
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp info using node@15.0.1 | win32 | x64
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python 
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python checking if "python3" can be used
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python checking if "python" can be used
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python checking if "python2" can be used
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python - "python2" is not in PATH or produced an error
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python checking if Python is C:\Python37\python.exe
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python - "C:\Python37\python.exe" could not be run
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python checking if Python is C:\Python27\python.exe
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python - "C:\Python27\python.exe" could not be run
[03/11/2020 à 15:55:12] [INFO] npm ERR!
[03/11/2020 à 15:55:12] [INFO]  gyp ERR! find Python checking if the py launcher can be used to find Python
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python - "py.exe" is not in PATH or produced an error
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python 
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python **********************************************************
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
[03/11/2020 à 15:55:12] [INFO] npm 
[03/11/2020 à 15:55:12] [INFO] ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python you can try one of the following options:
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
[03/11/2020 à 15:55:12] [INFO] npm ERR!
[03/11/2020 à 15:55:12] [INFO]  gyp ERR! find Python - Set the npm configuration variable python:
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python For more information consult the documentation at:
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! find Python **********************************************************
[03/11/2020 à 15:55:12] [INFO] npm ERR!
[03/11/2020 à 15:55:12] [INFO]  gyp ERR! find Python 
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! configure error 
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:302:47)
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:200:18)
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:266:16)
[03/11/2020 à 15:55:12] [INFO] npm
[03/11/2020 à 15:55:12] [INFO]  ERR! gyp ERR! stack     at exithandler (node:child_process:316:5)
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:328:5)
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:275:12)
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:465:16)
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:80:21)
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! System Windows_NT 10.0.15063
[03/11/2020 à 15:55:12] [INFO] npm
[03/11/2020 à 15:55:12] [INFO]  ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=c:\\Users\\coste\\.vscode\\extensions\\ibmblockchain.ibm-blockchain-platform-1.0.38\\node_modules\\grpc\\src\\node\\extension_binary\\electron-v9.2-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=c:\\Users\\coste\\.vscode\\extensions\\ibmblockchain.ibm-blockchain-platform-1.0.38\\node_modules\\grpc\\src\\node\\extension_binary\\electron-v9.2-win32-x64-unknown" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v9.2" "--dist-url=https://atom.io/download/electron"
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! cwd c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\node_modules\grpc
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! node -v v15.0.1
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! node-gyp -v v7.1.2
[03/11/2020 à 15:55:12] [INFO] npm ERR! gyp ERR! not ok 
[03/11/2020 à 15:55:12] [INFO] npm
[03/11/2020 à 15:55:12] [INFO]  ERR! node-pre-gyp ERR! build error 
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\node_modules\grpc\src\node\extension_binary\electron-v9.2-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\node_modules\grpc\src\node\extension_binary\electron-v9.2-win32-x64-unknown --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v9.2 --dist-url=https://atom.io/download/electron' (1)
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1048:16)
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.15063
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "c:\\Users\\coste\\.vscode\\extensions\\ibmblockchain.ibm-blockchain-platform-1.0.38\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp ERR! cwd c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\node_modules\grpc
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp ERR! node -v v15.0.1
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.14.0
[03/11/2020 à 15:55:12] [INFO] npm ERR! node-pre-gyp ERR! not ok
[03/11/2020 à 15:55:12] [INFO] npm
[03/11/2020 à 15:55:12] [INFO]  ERR! A complete log of this run can be found in:
[03/11/2020 à 15:55:12] [INFO] npm ERR!     C:\Users\coste\AppData\Local\npm-cache\_logs\2020-11-03T14_55_12_750Z-debug.log
[03/11/2020 à 15:55:12] [ERROR] Could not rebuild native dependencies Failed to execute command "npm" with  arguments "rebuild, grpc, --target=9.2.1, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed
[03/11/2020 à 15:55:12] [ERROR] Failed to activate extension: Error: Failed to execute command "npm" with  arguments "rebuild, grpc, --target=9.2.1, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1
[03/11/2020 à 15:55:12] [ERROR] Error: Failed to execute command "npm" with  arguments "rebuild, grpc, --target=9.2.1, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1
	at ChildProcess.<anonymous> (c:\Users\coste\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.38\build\extension\util\CommandUtil.js:76:39)
	at ChildProcess.emit (events.js:223:5)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

**Comment by Jakeeyturner** [comment]
Looks like node-gyp is complaining because it can't find python - please refer to https://github.com/nodejs/node-gyp#on-windows for their installation instructions.

Make sure you're using VS Code 1.39 as well and not any later (https://code.visualstudio.com/updates/v1_39)

**Comment by davidkel** [comment]
@BenCemlyon You can use a later version of VS Code than 1.39 on windows but you have to install the windows build tools required for node-gyp per the link provided by @Jakeeyturner above. However I see you are using node 15 and node 15 is not a supported version of node for this environment, I would recommend you install node 10 or node 12 instead.
